
POST http://localhost:8000/api/info/comment
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

{
    "content": "Here is another comment",
    "user": "674db4fb4bbab1ea44d0a4d7"

}